spring.application.name=thnal_youth_backend

spring.config.import=optional:file:${user.dir}/.env[.properties]

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never

jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
jwt.issuer=${JWT_ISSUER}
jwt.audience=${JWT_AUDIENCE}