spring.application.name=tnal_youth_backend

# Import environment variables from .env
spring.config.import=optional:file:.env

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/thnal_youth_db
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA & Hibernate settings
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable Docker Compose integration
spring.docker.compose.enabled=false

# Naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
