ALTER TABLE users
    ADD COLUMN IF NOT EXISTS role VARCHAR(50),
    ADD COLUMN IF NOT EXISTS status VARCHAR(30);

UPDATE users
SET role = COALESCE(role, 'MEMBER'),
    status = COALESCE(status, 'ACTIVE');

ALTER TABLE users
    ALTER COLUMN role SET NOT NULL,
ALTER COLUMN status SET NOT NULL;

